services:
  - type: web
    name: dicesuki
    runtime: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    repo: https://github.com/donovan-yohan/dicesuki
    branch: main
    plan: free
    envVars:
      - key: RUST_LOG
        value: info
